### ISSUE TITLE
 FR: Support download mp3 voice file when TTS

### ISSUE THREAD

**Issue by YIRU69** [VRCWizard/TTS-Voice-Wizard#1]
Hi! Thanks for you share.
Can support download mp3 voice file when TTS？

**Comment by VRCWizard** [comment]
This is not a planned feature at the moment but you could always record the audio with an external audio recording software.

**Comment by VRCWizard** [comment]
I'm gonna close this issue for now (not sure of the best practice for a feature request issue as to whether I should leave it open or not)
