### ISSUE TITLE
Api request faild

### ISSUE THREAD

**Issue by SunyiUborka** [VRCWizard/TTS-Voice-Wizard#12]
I tried several other region, generated multiple resources and tried several other version(0.7.9.5, 0.7.9.7, 0.8.0.1). 
![image](https://user-images.githubusercontent.com/59057829/196011840-b0840fb9-127f-4254-8055-b6b2d4cb4754.png)

**Comment by VRCWizard** [comment]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1692 alot of people are having issues with azure services after this most recent windows update. Solution is to uninstall the update "KB501xxxx" (it is different depending on your version of windows)
![image](https://user-images.githubusercontent.com/101527472/196012194-885ae058-9d60-4908-8f33-c02574e8e6af.png)

**Comment by VRCWizard** [comment]
![image](https://user-images.githubusercontent.com/101527472/196012228-42b43901-8ba5-49d7-9cb8-91d21a509543.png)

**Comment by VRCWizard** [comment]
The solution to this issue was already stated in the discord server help channel. That's where I usually answer issues since many of the users of my program are more proficient in using discord rather than GitHub. Just a PSA. https://discord.com/invite/YjgR9SWPnW
