### ISSUE TITLE
Found way get Quest 1 / 2 Battery Life - Requires ADB Stuff

### ISSUE THREAD

**Issue by NekoSuneVR** [VRCWizard/TTS-Voice-Wizard#14]
i found way pull Quest 2 Battery Life but it does Require ADB (Android Debug Bridge) to Detect Battery life.

to get battery life have to find way get Quest 2 Connect by Wired and Wireless using ADB in port 5555

mainly Oculus App uses ADB pull Quest 2 Battery Life and Controllers all direct headset and ADB calls it out.

so might be way get Quest and Quest 2 Supported and already fork Current Project today i see can find way intergrade it in and push changes with Quest 1/2 Integrations less someone else on it before me.

**Comment by ChisVR** [comment]
need some way pull this value `adb logcat | findstr /C:"serial" /C:"handedness" /C:"battery state"`

outputs controllers 

![image](https://user-images.githubusercontent.com/18028479/199219874-42f8051f-5f3a-4db0-8c19-af5abf8a7114.png)


so there is way do it, but using ADB is hardest i know of at moment

**Comment by VRCWizard** [comment]
Interesting, I'll have to do some research.

**Comment by ChisVR** [comment]
@VRCWizard far as i can go is, ALVR can pull out Quest 2 Cointrollers and Headset Battery

t comes wireless app to Quest 1 / 2 using APK file and it does pull out Battery life on it already.

so can go 2 ways is make it support ALVR or do custom ADB way.

i send you screenshot in sec i need reinstall ALVR show you

**Comment by ChisVR** [comment]
![image](https://user-images.githubusercontent.com/18028479/202280515-b0d01675-4415-4146-9568-ccc3eb5b3dc1.png)
![image](https://user-images.githubusercontent.com/18028479/202280734-9ca514ea-88e0-4a00-b93f-630d649e6cc5.png)
![image](https://user-images.githubusercontent.com/18028479/202281435-c9255e60-6aae-4795-b87b-c2b442a264e3.png)
it be better pull out battery without people need buy XSOverlay, only managed get XSOverlay today just test it.

**Comment by VRCWizard** [comment]
Example program to send quest data to TTS Voice Wizard: https://github.com/VRCWizard/Quest2-TTSVoiceWizard
