### ISSUE TITLE
Auto Clear TTS Text Box Field not functioning after latest update

### ISSUE THREAD

**Issue by just-iida** [VRCWizard/TTS-Voice-Wizard#21]
Version: v0.9.4.6
OS: Win10

After the latest update, the text box does not clear itself after TTS.
I've checked that the toggle is on and tried with it toggle off as well. Also tried extracting the zip file again with same results.

**Comment by just-iida** [comment]
Fixed in [commit 7029b](https://github.com/VRCWizard/TTS-Voice-Wizard/commit/7029b)

**Comment by VRCWizard** [comment]
I quickly realized that previous commit caused the tts box to clear on STT actions too so I fixed that issue in the latest [commit](https://github.com/VRCWizard/TTS-Voice-Wizard/commit/f36e3b4a6117b1a14b05d674c27578ad1aa7ed9b)
