### ISSUE TITLE
TTS OBS plugin using Text Source

### ISSUE THREAD

**Issue by oo22339** [VRCWizard/TTS-Voice-Wizard#22]
I would like to make a suggestion here.  This is about OBS.  
I am currently using Closed Captioning via Google Speech Recognition 0.0.8.
This plug-in converts my voice into text in real time.
This text is entered as an OBS text source and disappears after a while.
I want to convert this real-time text into AI voice and send it to the broadcast using this text source.
Currently, in your wizard program, you have to input text directly from the program to the keyboard to convert it into voice. 
Can you create an OBS plug-in that takes the text source of OBS and converts it into voice in real time?

**Comment by VRCWizard** [comment]
This feature has been added in the latest release 
![image](https://user-images.githubusercontent.com/101527472/234433799-0707cf4e-b8db-4296-98ce-c4762a599fda.png)

It will play the text in the file when it is modified.
