### ISSUE TITLE
Web Captioner Speech to Text hook, always skips the first word.

### ISSUE THREAD

**Issue by DaemonCross** [VRCWizard/TTS-Voice-Wizard#23]
Hi, I've been trying the web captioner hook. And no matter how long or short the recognized speech is. TTS wizard ignores the first word.

And on related note, Sometimes It repeats the sentences as individual words.

Webhook is also set to 4-5 word batches, so short sentences should be sent instead of individual words.

**Comment by VRCWizard** [comment]
https://github.com/VRCWizard/TTS-Voice-Wizard/wiki/Web-Captioner "as the Webhook URL and experiment with different chunking values (I recommend a large value so it only sends when you finish talking)." You have to change chunking to a "large value" sorry if this wasn't clear. 

![image](https://user-images.githubusercontent.com/101527472/219952368-e2c49a6b-046a-40ce-9dde-85c42fb0a429.png)

**Comment by DaemonCross** [comment]
Hi, Epic quick on the replies! haha.

Yeah, I have tried larger chunk values 4-10. But the results are the same where the first word gets lopped off. I've also tried your value of 30. And ill will upload the screen side by what web caption picked up and what the latest tts build output.

**Comment by DaemonCross** [comment]
[https://snipboard.io/rpeSX8.jpg](url)

**Comment by VRCWizard** [comment]
Not as quick this time sorry. I'm not sure what would be causing this. Could you try resetting your web captioner settings to default and re-adding the webhook.  The only think I could think of is that web captioner has trouble hearing you on your first word and does a word replace on the transcript. (when words are replaced in web captioner they may not appear in the webhook transcript used by TTS Voice Wizard)

**Comment by VRCWizard** [comment]
If you haven't already, also make sure you have tried re-opening web captioner and tts voice wizard.

**Comment by DaemonCross** [comment]
Hi again,

Alright, so web captioner is started with no login on a fresh chrome profile, only reduced the font size to clearly see i tried different start words with same following sentence "truncation check". TTS wizard also fresh restarted, as you can see below...

Same symptoms, the first word gets lopped off, regardless of me changing them to different inflections.

**Comment by DaemonCross** [comment]
![222](https://user-images.githubusercontent.com/125807337/220004327-f2976062-468d-4a41-9066-a71da6c4669e.png)

**Comment by VRCWizard** [comment]
I'm not sure what the issue is, nothing should be cut off. I've tried it on 2 computers and double checked the code. You can try a different recognition method like vosk! I'll make this as a bug although i'm not sure how to replicate the issue.

**Comment by DaemonCross** [comment]
VRC,
Aight, Thank you for looking into this. I'm weirded out as well. As layman logic says, if text on screen is right. It should also be sent word for word. Right? I figured a work around for this glitch by saying a throw word "Say or Said" then the sentence to be voiced. Seems to be workable, for now.

Anyway, I'll give Vosk! a go if its free. haha. But may take me a bit.

**Comment by VRCWizard** [comment]
I recommend joining the discord with anymore questions, I give quicker help on the fly in there.  https://discord.com/invite/YjgR9SWPnW
