### ISSUE TITLE
Other .NET components not optional

### ISSUE THREAD

**Issue by CrashCat** [VRCWizard/TTS-Voice-Wizard#26]
Updated to the 1.0.3 version today, I think i was on 0.9.9 before.  Anyway I got the .NET error again like you warned in the 1.0.2 release notes.  However, it would not start after installing the package from that error message.  I installed the x86 package for console apps and after that it also still would not start.  After I installed the Hosting Bundle it started normally.  I've never used Fonixtalk/Moonbase but apparently it must be checking for that dependency before it will even launch.

**Comment by VRCWizard** [comment]
those 2 that you downloaded arent required for the program to operate. (x86 console and hosting bundle). You should have been prompted to download this https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.14-windows-x64-installer?cid=getdotnetcore

![image](https://user-images.githubusercontent.com/101527472/222935440-3edfe005-f318-47ac-8f34-a5e31891d530.png)
I've added this to the QuickStart guide. Sorry for the confusion, let me know if you are still having trouble after downloading that.

**Comment by CrashCat** [comment]
Yeah, I understand that is what you wrote in the notes, I am reporting that it didn't work that way.  

I could not launch the app until I had all three installs.  The ASP.NET Core was not enough, and the x64 console apps package was also not enough.  It gave me the same popup error telling me to install ASP.NET Core until I had all three packages installed, even when I had ASP.NET Core installed.  

I do have one other machine to test it on and I couldn't reproduce it there, I only had to have the Desktop Runtime (like before) and the ASP.NET Core.  So I am hoping it's some complication due to having used the app before.  

I actually did try a fresh copy of the newest version unzipped to a totally separate folder before I downloaded any extra components besides ASP.NET Core on the PC that I had been using the app on, but that didn't help and that was the PC where it insisted I had to get the other two new components.  I am guessing it reads some shared configuration or something and decided not to launch. 

The weird thing about the whole mess is I was just getting the ASP.NET Core error repeatedly, it never told me about the other two packages and I actually mistakenly downloaded the Core a second time before I read the error message more carefully, so I was stuck in some sort of weird state where I was missing something it wanted but it couldn't tell me what it wanted.  That's when I originally went back through the release notes to find out about the other new components. 

Honestly I am guessing it's not something you can actually hunt down and fix but thought you might want to know since it could be a blocker for people updating a previous installation.

**Comment by VRCWizard** [comment]
Ah alright good to know. I'll mention this in the Quickstart guide. There is also a discord guide where I inform people more often about any issues or updates. https://discord.com/invite/YjgR9SWPnW
