### ISSUE TITLE
All fields on Speech to TTS are not saved on app closing

### ISSUE THREAD

**Issue by Malachiel87** [VRCWizard/TTS-Voice-Wizard#3]
I would like all changed field on Speech to TTS menu will be saved on app closing, Thank you <3

**Comment by VRCWizard** [comment]
This has been on the TODO list, for a while consider it done, will update it later today

**Comment by VRCWizard** [comment]
gonna delay the update a bit, ill keep the issue open until then.

**Comment by VRCWizard** [comment]
https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v0.5.5 feature included in preview build.

**Comment by Malachiel87** [comment]
Working, thank you <3
