### ISSUE TITLE
Suggestion: Audio volume percentage level for TTS

### ISSUE THREAD

**Issue by Whyareuhere** [VRCWizard/TTS-Voice-Wizard#31]
While the TTS is great to use, there is a lack of being able to control the volume in the TTS Voice Wizard itself. The GLADOS one comes out at a very high volume. Having a simple volume slider for the TTS would solve this issue

**Comment by VRCWizard** [comment]
![image](https://user-images.githubusercontent.com/101527472/233895129-a42936f9-7af2-47e6-a06f-7da0983e2904.png)
There is one, Although it may need to be adjusted to use a scale from 0-100 rather than being that same as the speed and pitch implementations.
