### ISSUE TITLE
Music Update problem with youtube

### ISSUE THREAD

**Issue by ShadowBunni** [VRCWizard/TTS-Voice-Wizard#33]
when playing music thru YouTube, it'll show the first song your listening to and the what min and sec your on if you have it showing that and upon updating the text it'll show the same thing indefinitely until i restart the app. Pls get this fixed asap

**Comment by VRCWizard** [comment]
This is a known issue, that affects a very small portion of users. Possibly related to this issue https://github.com/DubyaDude/WindowsMediaController/issues/6 .  I'll attempt the recommended fix in this thread and add it to the next prerelease for those experiencing the issue to test.

**Comment by VRCWizard** [comment]
https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v1.2.3.6 possible fix, if you do try it make sure to read the release notes and let me know if it works or not.
