### ISSUE TITLE
Issue about Whisper Model recognition Chinese

### ISSUE THREAD

**Issue by XieLongWu** [VRCWizard/TTS-Voice-Wizard#36]
I have tested almost all whisper models of all sizes, and similar things happen. 
When the recognition input language is set to Chinese. 
When there is no voice input, the whisper model will continue to output spam, but if it is set to English, there will be no similar issue. 
Japanese has not found the same issue, and I have not tried other languages.
Then I tried to switch the model to vosk, and there was no similar issue.

When I set the input to a microphone without any signal input, as can be seen in the screenshot, the whisper models output garbage.
![TTSVoiceWizard_2023-06-21_13-06-43](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/57319089/928d288b-22b8-45ff-b5be-5b9fbce244fe)

This issue occurs more often when the mic is set to the one that I everyday use at the time I don't say anything

I don't know what caused this problem. I tried to use text replacement to delete these spam messages, but he often randomly combined some common words and randomly added spaces, which made it basically unusable.

I checked Whisper Model's github, as well as some technology shares using Whisper Model directly. 
But there seems to be no such problem. 
It seems that Whisper Model can be set to recognize multiple languages at the same time. 
Is it possible to manually add startup commands, or provide an option to select multiple languages? 
I wonder if this problem will be eliminated when multiple languages are recognized at the same time.

**Comment by VRCWizard** [comment]
This is an issue with the package I use https://github.com/Const-me/Whisper/issues/54 , where it hallucinates words where there are non. I'll be looking into adding a similar solution as proposed in this issue.
