### ISSUE TITLE
Cant find some tts

### ISSUE THREAD

**Issue by Adovka** [VRCWizard/TTS-Voice-Wizard#40]
I tried several other TTS on this programm, but some are not working, the most important to me is "Acapela Elan TTS Digalo Nikolai", even though its SAPI5, its just not on the list

**Comment by VRCWizard** [comment]
Hello, I've been researching this topic a bit and came to some conclusions:
In general on a 64 bit system voices seem to be stored in 3 places:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices (i'll refer to this as SPEECH)
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices  (i'll refer to this as Speech_OneCore)
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Speech\Voices (i'll refer to this as WOW6432Node)

The latest version of TTS Voice Wizard that is 64 bit only seems to pull voices from SPEECH.


When you download some of these voices they seem to download to Wow6432Node by default indicating they are meant to be used for 32 bit app and cannot be used in 64 bit apps.
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/264f146c-8d29-4593-bbe3-3a448b6259ce)

When trying a 32bit version of TTS Voice Wizard such as [TTSVoiceWizard-v0.9.3-x86](https://github.com/VRCWizard/TTS-Voice-Wizard/releases/download/v0.9.3/TTSVoiceWizard-v0.9.3-x86.zip), the voices inside WOW6432Node appear although in my testing the voice would say "Cannot set voice. No matching voices is installed or the voice was disabled" and it could not be used.
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/0b3090b6-6890-4a36-9ebf-59f76f03f102)



You could change the change the path for the download voice to be SPEECH although the voice still wouldn't work.
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/f48d7749-4ec4-48ce-9de2-d31acd57c2f3)

Example from windows built in Speech Properties
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/c6e82a6b-695b-4d28-8934-9c9ad86d1363)


This is likely an issue with voices just being incompatible with https://msdn.microsoft.com/en-us/library/system.speech.synthesis(v=vs.110).aspx the API used in TTS Voice Wizard / Windows to play SAPI5 voices. 

Alright so, if you download a 32 bit version of TTS Voice Wizard see if more of your voices appear. Although some voices that were in SPEECH may not appear. Test if you can actually use any of the voices. I've gone through many posts and I am stumped.

In conclusion, the voices probably won't be supported unless some type of work around is found. 

Sources: 
https://stackoverflow.com/questions/61286719/all-text-to-speech-installed-voices-not-showing-up
https://stackoverflow.com/questions/3208617/speechsynthesizer-doesnt-get-all-installed-voices
https://stackoverflow.com/questions/31704614/universal-apps-template-missing-in-visual-studio-2015-community
https://stackoverflow.com/questions/51811901/speechsynthesizer-doesnt-get-all-installed-voices-3
https://superuser.com/questions/1327732/using-32-bit-tts-voices-on-windows-7-64-bit
https://social.technet.microsoft.com/Forums/windows/en-US/c7409091-087e-48f2-8178-bcd918799054/add-tts-voice-to-windows-7-and-set-as-default?forum=w7itproinstall

Where I downloaded the 32 bit voice to test with: https://www.youtube.com/watch?v=ntDdtnpt1oo&t=205s&ab_channel=Waleedarix%27sAlt
