### ISSUE TITLE
Can't find my language in spoken language list

### ISSUE THREAD

**Issue by Ezrabro** [VRCWizard/TTS-Voice-Wizard#41]
I speak Persian , so i checked whisper and saw that it supports my language

![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/67427897/d5c6ae27-05e7-46b2-869c-efbb95de2f4c)

but i can't find it in the list 

![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/67427897/6b071697-3bf7-4586-a70d-bdfef99fc81f)

how can i change this into Persian?

**Comment by VRCWizard** [comment]
Here is a pre-release that includes Persian as a language for Whisper STT (Speech-to-Text) and Azure STT, additionally some Persian Text-to-Speech voices have been added for use with Microsoft Azure.

https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v1.4.8
