### ISSUE TITLE
Remembering the last used presets

### ISSUE THREAD

**Issue by chrisk414** [VRCWizard/TTS-Voice-Wizard#42]
Hi, there! 
I have a small request. 

Every time when I use the app, I have to change the preset, for example, "Text to Speech" -> "Presets" always go back to "Non Selected"
Is it possible to remember "Preset"? 

Thanks.

**Comment by VRCWizard** [comment]
https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v1.4.9

Preset is now saved

**Comment by chrisk414** [comment]
Wow so fast! Thank you very much!
