### ISSUE TITLE
[BUG] STT (whisper)

### ISSUE THREAD

**Issue by chrisk414** [VRCWizard/TTS-Voice-Wizard#43]
Hi, there! Using STT (whisper), I found a couple of bugs.  (I'm running the app on Visual Studio 2022 Debug)

1. Click on "Speech to Text to Speech" on/off several times will cause the Exception Error.
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/752887/4bb3691f-4b67-47a3-b488-525551588f20)

2. Closing the app (pressing "" icon) with "Speech to Text to Speech" Enabled, will not kill the app. There are dangling thread remaining preventing the app to exit.  You will see this behavior when the app is launched from Visual Studio Debug. 

I think that's all for now and many thanks for the wonderful app.

**Comment by VRCWizard** [comment]
1. I've applied a possible fix, I couldn't get the error to display for myself after a couple tries although it could still be there.

2. Fixed, recognizers are now stopped on form closing

https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v1.4.9

**Comment by chrisk414** [comment]
You are really wonderful. I'm so happy that I got to know this app and I'll try to help as much as I can to make this app better. I think the possibility of this app is limitless. I'm pretty sure you are thinking the same. ^^

**Comment by chrisk414** [comment]
Hi, here is the update. 

# 1. Still seems to be the issue. Just to let you know. ^^
# 2.  has been fixed. Great!

Cheers!

**Comment by VRCWizard** [comment]
1. Whisper can now NOT be stopped while it is launching to help avoid the AccessViolationException. If you can still reproduce the issue let me know the scenario.
 https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v1.5.1

**Comment by chrisk414** [comment]
Sure, I'll. 

Oh, there is compilation error at
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/752887/88e7d364-ad69-40a1-96fd-1fb3cf0e1ebb)

missing, comboBoxProBranch.  ^^

**Comment by chrisk414** [comment]
Thanks. It compiles. 👍

**Comment by VRCWizard** [comment]
Although it is still possible to cause error 1. to happen the likelihood has been drastically reduced by preventing users from stopping Whisper during it's startup so I'll be closing this issue.
