### ISSUE TITLE
[TTS Glitch] TTS Says Stuff Twice

### ISSUE THREAD

**Issue by TsukiakariMitsuki** [VRCWizard/TTS-Voice-Wizard#47]
Hi uhm, im having an issue with the TTS system i've never experienced before, upon pressing enter to make the program do the TTS process.. its, doubled, lemme try to explain it the best i can, instead of hearing the TTS say the text i inputted only once, i hear it twice, the second time with some slight delay than the first time, its a lil weird and idk why this is happening.

Clip of this happening: https://streamable.com/rsh7fc

Any help with this would be appreciated- (this is my first time ever making a post on github btw lol)

**Comment by VRCWizard** [comment]
Please read through the audio setup instruction: 
https://github.com/VRCWizard/TTS-Voice-Wizard/wiki/Virtual-Cable#how-to-output-tts-through-a-microphone

https://youtu.be/Q4kaXcA74Bo?t=86

My guess is either you set 1st and 2nd output device to the same device or you have listen to device on in control panel sound for the virtual cable.
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/19ae4b79-1b98-4012-9889-156ab004ab1e)
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/cdb63c4b-5d8d-4cdc-b93a-dc69544a06ea)
