### ISSUE TITLE
Adding Our Own Custom Voice

### ISSUE THREAD

**Issue by sterelok123** [VRCWizard/TTS-Voice-Wizard#52]
Hi.

Would you add the option so that we can add our own .pth RVC voice file to it to use as basis for our STTTS?

Thank you.

**Comment by VRCWizard** [comment]
Sorry for the delay, I've finally had the time to do research into RVC.

You could use any voice changer in conjunction with TTS Voice Wizard, here are instructions for installing and using a RVC voice changer that I have tested: https://youtu.be/_JXbvSTGPoo?si=CIi2ItR7KPwt0d1W


For "connecting" the two apps its just simple audio routing... you speak (or type) into TTS Voice Wizard then pass that audio into the voice changer then the audio from the voice changer goes where every you want it.

[actual microphone] --> [TTS Voice Wizard] --> [Virtual Cable 1] --> [voice changer] --> [Virtual Cable 2] --> [Game]

here is an example video:

https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/05ffe8dd-6494-4c42-abd3-c5dde2c60564
