### ISSUE TITLE
Wiki update: install with scoop (package manager)

### ISSUE THREAD

**Issue by babo4d** [VRCWizard/TTS-Voice-Wizard#56]
[Scoop](https://scoop.sh/) is a command-line installer for windows that is well-suited to managing portable apps like this one. Scoop users can install the app from my [scoop bucket](https://github.com/babo4d/scoop-xrtools).

You can add a note to the wiki about installing with scoop, which only requires a couple of commands:

```
scoop bucket add xrtools "https://github.com/babo4d/scoop-xrtools"
scoop install tts-voice-wizard
```

The scoop installation also creates a start menu shortcut, recommends the user to install VB-CABLE, and provides instructions on how to install the .NET desktop runtime dependency with scoop:

```
> scoop info tts-voice-wizard
...
...
Suggestions : extras/windowsdesktop-runtime-lts
Notes       : Some features require a virtual audio cable like VB-CABLE <https://vb-audio.com/Cable/>
              Requires .NET Desktop Runtime 6.0. To install with scoop:
                scoop install sudo
                sudo scoop install windowsdesktop-runtime-lts
```

I have submitted the manifest to the scoop `Extras` repository (https://github.com/ScoopInstaller/Extras/pull/11918) which would further simplify installation and improve discoverability.

**Comment by babo4d** [comment]
Package was accepted into the `extras` bucket so instructions can be simplified to:

```
scoop install extras/tts-voice-wizard
```

**Comment by VRCWizard** [comment]
added to readme as alternative installation method
https://github.com/VRCWizard/TTS-Voice-Wizard/commit/287b1b968ee40854b7b0802d14798a95e924e40b
