### ISSUE TITLE
OBSText File Error

### ISSUE THREAD

**Issue by sophienix** [VRCWizard/TTS-Voice-Wizard#59]
i am getting [OBSText File Error: Could not find a part of the path 'C:\Users\User\Desktop\TTSVoiceWizard-v1.5.8.1-x64\Output\TextOut\OBSText.txt'.. Try moving folder location.] it was in downloads but no matter where i move tts voice it dose it I also run it as administrator it even did it befor i updated as well i can click open file location and it works it just wont update / overwrite the txt file

**Comment by sophienix** [comment]
no it was in downloads it did not need admin

**Comment by VRCWizard** [comment]
please provide a screenshot of the current error message you are receiving if you still require assistance.
