### ISSUE TITLE
[Bug] Spotify outputting periodically when it shouldn't

### ISSUE THREAD

**Issue by TheVania** [VRCWizard/TTS-Voice-Wizard#6]
There appears to be a bug where spotify periodically outputs when the setting to do so is disabled, except without the current time.

This happens when "Send Text to VRChat with KAT" is disabled.

**Comment by VRCWizard** [comment]
fixed https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v0.6.6.1 . Thank you for letting me know about this.

**Comment by VRCWizard** [comment]
This fix introduced another bug where if both KAT and VRC Chatboxes are activated the KAT output doesn't refresh when changing songs, ill fix this for the next release!

**Comment by TheVania** [comment]
> This fix introduced another bug where if both KAT and VRC Chatboxes are activated the KAT output doesn't refresh when changing songs, ill fix this for the next release!

There appears to be another bug that may or may not be related, but Continuous Recognition appears to not send the OSC and disabling it makes the  keybind throw an error and requires a program restart.

**Comment by VRCWizard** [comment]
issue fixed, ill address Spotify outputting when paused at a later date. (Maybe make it show that it is paused or stop outputting if (previous output matches recent output basically)
