### ISSUE TITLE
Old version was good now its getting wrose

### ISSUE THREAD

**Issue by Samthapa76** [VRCWizard/TTS-Voice-Wizard#69]
old version there was optimus prime in english now portuguise ? and mexican WTH and now less voices its bad ill delete it and never going to use it

**Comment by VRCWizard** [comment]
TikTok removed the voice from their API https://github.com/oscie57/tiktok-voice/issues/1#issuecomment-1728663837 buddy. 

![hqdefault](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/e6a26e87-3061-46cd-82fd-093ab55d21c1)
