### ISSUE TITLE
[Feature Request] Show the typing dots when TTS is listening or while typing in the text box

### ISSUE THREAD

**Issue by TheVania** [VRCWizard/TTS-Voice-Wizard#7]

**Comment by VRCWizard** [comment]
added https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v0.6.8

**Comment by TheVania** [comment]
Bubble pops up when typing in the text box now but not when the button bind is hit. Additionally this isn't really an issue but the bubble for pressing the STTTS is really short.

Thinking it should show for as long as it's listening for.
