### ISSUE TITLE
Azure Cognitive Services explicit punctuation settings

### ISSUE THREAD

**Issue by potato-owo** [VRCWizard/TTS-Voice-Wizard#76]
Could you please add to the UI and Azure speech provider the settings for explicit punctuation?

For continuous recognition (only), the setting would be enabled with:
`speechConfig.EnableDictation();`
reference: https://learn.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechconfig?view=azure-node-latest#microsoft-cognitiveservices-speech-sdk-speechconfig-enabledictation

Otherwise, for non-continuous recognition, it must be set with:
`speechConfig.SetServiceProperty("punctuation", "explicit", ServicePropertyChannel.UriQueryParameter);`
reference: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/667#issuecomment-690840772

With EnableDictation or explicit punctuation, users have finer control of punctuation returned in the recognized result.

It could default to automatic punctuation as it is now, but when set, users need to say in their sentences "question mark", "comma", "period", etc for these punctuation marks to be included in the text.

**Comment by VRCWizard** [comment]
added: https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v1.6.9.5

It is disabled by default, find the option under Speech Provider > Azure Cognitive Services
![image](https://github.com/VRCWizard/TTS-Voice-Wizard/assets/101527472/3161e9fe-736c-4ac6-8b7f-3e2f32b7dc63)
