### ISSUE TITLE
Missing Spotify Feature in compact mode in test version

### ISSUE THREAD

**Issue by TheVania** [VRCWizard/TTS-Voice-Wizard#8]
Just wanted to make this known just in case it isn't.

Compact mode doesn't display current duration with "Output Current Song Periodically" is enabled.

Also it isn't compact upon switching songs

Additionally, add support for the hour mark if possible (only if song length >1hr, otherwise hide hour mark), as when I added local files that are long mixes, it doesn't display the hour mark.

**Comment by VRCWizard** [comment]
https://github.com/VRCWizard/TTS-Voice-Wizard/releases/tag/v0.6.9 all items addressed
